/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingsRouteImport } from './routes/trainings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as MyTrainingsRouteImport } from './routes/my-trainings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingsIdRouteImport } from './routes/trainings_.$id'

const TrainingsRoute = TrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTrainingsRoute = MyTrainingsRouteImport.update({
  id: '/my-trainings',
  path: '/my-trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingsIdRoute = TrainingsIdRouteImport.update({
  id: '/trainings_/$id',
  path: '/trainings/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/my-trainings': typeof MyTrainingsRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/trainings': typeof TrainingsRoute
  '/trainings/$id': typeof TrainingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/my-trainings': typeof MyTrainingsRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/trainings': typeof TrainingsRoute
  '/trainings/$id': typeof TrainingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/my-trainings': typeof MyTrainingsRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/trainings': typeof TrainingsRoute
  '/trainings_/$id': typeof TrainingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/my-trainings'
    | '/referral'
    | '/register'
    | '/trainings'
    | '/trainings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/my-trainings'
    | '/referral'
    | '/register'
    | '/trainings'
    | '/trainings/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/my-trainings'
    | '/referral'
    | '/register'
    | '/trainings'
    | '/trainings_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  MyTrainingsRoute: typeof MyTrainingsRoute
  ReferralRoute: typeof ReferralRoute
  RegisterRoute: typeof RegisterRoute
  TrainingsRoute: typeof TrainingsRoute
  TrainingsIdRoute: typeof TrainingsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainings': {
      id: '/trainings'
      path: '/trainings'
      fullPath: '/trainings'
      preLoaderRoute: typeof TrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trainings': {
      id: '/my-trainings'
      path: '/my-trainings'
      fullPath: '/my-trainings'
      preLoaderRoute: typeof MyTrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainings_/$id': {
      id: '/trainings_/$id'
      path: '/trainings/$id'
      fullPath: '/trainings/$id'
      preLoaderRoute: typeof TrainingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  MyTrainingsRoute: MyTrainingsRoute,
  ReferralRoute: ReferralRoute,
  RegisterRoute: RegisterRoute,
  TrainingsRoute: TrainingsRoute,
  TrainingsIdRoute: TrainingsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
